modLoader="fabric"
loaderVersion="[0.14.0,)"
license="MIT"
minecraft="1.20.1"
author="Zhang1233"
contactUrl="https://github.com/Zhang12334/MeowAutoResourcePack/issues"
issues="https://github.com/Zhang12334/MeowAutoResourcePack/issues"

[[mods]]
modId="meowautoresourcepack"
version="1.0.0"
description="A mod to automatically download and install resource packs."
displayName="Meow Auto Resource Pack"
icon="assets/meowautoresourcepack/icon.png"
authors="YourName"

[[dependencies]]
modId="fabric-api"
mandatory=true
version="[0.76.0+1.20,)"
