name: Build Mod with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (using Temurin)
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # 使用 Temurin 版本的 JDK

      # Step 3: Install Gradle (if needed)
      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      # Step 4: Generate Gradle Wrapper
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      # Step 5: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 6: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MeowAutoResourcePack
          path: build/libs/*.jar
